                               ;File generated by dasmZ80.jar Z80 disassembler from testWriteOutput.hex

       .org 0x0000

start: NOP                     ;comment
       HALT                    ;comment
       .end
