package com.github.hanwelmer.dasmZ80;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Z80 disassembler, written in Java.
 */
// Known limitations:
// - Input file must be in binary format (Intel Hex format not supported yet).
// - Input filename must have extension bin.
// - Start address is assumed to be 0x0000 (no CLI parameter yet to define start
// address).
// - Binary code is assumed to be Z80 compatible (no CLI parameter yet to define
// type of processor).
// - Disassembler stops at first unrecognized or illegal opcode (No input file
// yet to define addresses or ranges for data blocks).
// - Output in listing format (no CLI parameter yet to select assembler or
// listing output format).
// - Output is to system output (screen or pipe) (no CLI argument yet to define
// output filename).
public class DasmZ80 {
  /**
   * The main method. See usage() for a functional description.
   * 
   * @param args
   *          the argument list.
   */
  public static void main(String[] args) {
	// process command line options and arguments.
	if (args.length == 1) {
	  String fileName = args[args.length - 1];
	  if (fileName.endsWith(".bin")) {
		// do the main work.
		disassemble(fileName);
	  } else {
		usage();
	  }
	} else {
	  usage();
	}
  } // main()

  private static void usage() {
	System.out.println("Usage: java -jar dasmZ80.jar filename.ext");
	System.out.println(" where filename.ext is file to be disassembled");
	System.out.println(" which must have extension .bin");
	System.out.println(" which must be in binary format.");
	System.out.println(" Binary code is assumed to be Z80 compatible.");
	System.out.println(" Start address is assumed to be 0x0000.");
	System.exit(1);
  } // usage()

  protected static void disassemble(String fileName) {
	BinFileReader reader = new BinFileReader();
	try {
	  reader.open(fileName);
	  writeOutput(fileName, disassemble(fileName, reader));
	} catch (FileNotFoundException e) {
	  System.out.println("Error opening file " + fileName);
	  System.out.println(e.getMessage());
	  e.printStackTrace();
	} finally {
	  reader.close();
	}
  } // disassemble()

  protected static void writeOutput(String fileName, HashMap<Integer, AssemblyCode> decoded) {
	ListingWriter lstWriter = new ListingWriter();
	try {
	  lstWriter.open(fileName);
	  writeOutput(fileName, lstWriter, decoded);
	} catch (IOException e) {
	  System.out.println(e.getMessage());
	  e.printStackTrace();
	} finally {
	  if (lstWriter != null) {
		lstWriter.close();
	  }
	}
  } // writeOutput()

  private static void writeOutput(String fileName, ListingWriter lstWriter, HashMap<Integer, AssemblyCode> decoded)
      throws IOException {
	String msg = String.format(";File generated by dasmZ80.jar Z80 disassembler from %s\n", fileName);
	lstWriter.write(new AssemblyCode(0, "", msg));
	boolean doOrigin = true;
	for (Map.Entry<Integer, AssemblyCode> entry : decoded.entrySet()) {
	  if (doOrigin) {
		lstWriter.write(new AssemblyCode(0, String.format(".org 0x%04X\n", 0)));
		doOrigin = false;
	  }
	  lstWriter.write(entry.getValue());
	}
	lstWriter.write(new AssemblyCode(0, ".end"));
  } // writeOutput()

  protected static HashMap<Integer, AssemblyCode> disassemble(String fileName, ByteReader reader) {
	Decoder decoder = new Decoder();
	HashMap<Integer, AssemblyCode> decoded = new HashMap<Integer, AssemblyCode>();
	int address = 0;
	Byte nextByte = null;

	try {
	  while ((nextByte = reader.getByte()) != null) {
		AssemblyCode asmCode = decoder.get(address, nextByte, reader);
		decoded.put(address, asmCode);
		address += asmCode.getBytes().size();
	  }
	} catch (IOException e) {
	  System.out.println("Error reading from input file.");
	  System.out.println(e.getMessage());
	  e.printStackTrace();
	}
	return decoded;
  } // disassemble()

}
