package com.github.hanwelmer.dasmZ80;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.SortedSet;
import java.util.TreeSet;

/**
 * Z80 disassembler, written in Java.
 */
// Known limitations:
// - Input file must be in binary format (Intel Hex format not supported yet).
// - Input filename must have extension bin.
// - Start address is assumed to be 0x0000 (no CLI parameter yet to define start
// address).
// - Binary code is assumed to be Z80 compatible (no CLI parameter yet to define
// type of processor).
// - Disassembler stops at first unrecognized or illegal opcode (No input file
// yet to define addresses or ranges for data blocks).
// - Output in listing format (no CLI parameter yet to select assembler or
// listing output format).
// - Output is to system output (screen or pipe) (no CLI argument yet to define
// output filename).
public class DasmZ80 {
  /**
   * The main method. See usage() for a functional description.
   * 
   * @param args
   *          the argument list.
   */
  public static void main(String[] args) {
	// process command line options and arguments.
	if (args.length == 1) {
	  String fileName = args[args.length - 1];
	  if (fileName.endsWith(".bin")) {
		// do the main work.
		disassemble(fileName);
	  } else {
		usage();
	  }
	} else {
	  usage();
	}
  } // main()

  private static void usage() {
	System.out.println("Usage: java -jar dasmZ80.jar filename.ext");
	System.out.println(" where filename.ext is file to be disassembled");
	System.out.println(" which must have extension .bin");
	System.out.println(" which must be in binary format.");
	System.out.println(" Binary code is assumed to be Z80 compatible.");
	System.out.println(" Start address is assumed to be 0x0000.");
	System.exit(1);
  } // usage()

  protected static void disassemble(String fileName) {
	BinFileReader reader = new BinFileReader();
	ListingWriter lstWriter = new ListingWriter();
	try {
	  reader.open(fileName);
	  lstWriter.open(fileName);
	  disassemble(fileName, reader, lstWriter);
	} catch (FileNotFoundException e) {
	  System.out.println("Error opening file " + fileName);
	  System.out.println(e.getMessage());
	  e.printStackTrace();
	} catch (IOException e) {
	  System.out.println(e.getMessage());
	  e.printStackTrace();
	} finally {
	  reader.close();
	  if (lstWriter != null) {
		lstWriter.close();
	  }
	}
  } // disassemble()

  protected static HashMap<Integer, AssemblyCode> disassemble(String fileName, ByteReader reader,
      AbstractWriter writer) {
	Decoder decoder = new Decoder();
	HashMap<Integer, AssemblyCode> decoded = new HashMap<Integer, AssemblyCode>();
	int address = 0;
	int lineNr = 0;
	Byte nextByte = null;

	try {
	  while ((nextByte = reader.getByte()) != null) {
		AssemblyCode asmCode = decoder.get(address, nextByte, reader);
		decoded.put(++lineNr, asmCode);
		address += asmCode.getBytes().size();
		if (asmCode.getMnemonic().startsWith("RET")) {
		  decoded.put(++lineNr, new AssemblyCode(address, ""));
		}
	  }
	  writeOutput(fileName, writer, address, decoded);
	} catch (IllegalOpcodeException e) {
	  System.out.print(e.getMessage() + "\n");
	  decoded.put(++lineNr, new AssemblyCode(address, e.getMessage()));
	  decoded.put(++lineNr, new AssemblyCode(0, ""));
	  writeOutput(fileName, writer, address, decoded);
	  writeRemainderOfInput(address, reader, writer);
	} catch (IOException e) {
	  System.out.println("Error reading from input file.");
	  System.out.println(e.getMessage());
	  e.printStackTrace();
	}
	return decoded;
  } // disassemble()

  protected static void writeOutput(String fileName, AbstractWriter writer, int address,
      HashMap<Integer, AssemblyCode> decoded) {
	String msg = String.format(";File generated by dasmZ80.jar Z80 disassembler from %s", fileName);
	try {
	  writer.write(new AssemblyCode(0, "", msg));
	  writer.write(new AssemblyCode(0, ""));
	  boolean doOrigin = true;
	  SortedSet<Integer> keys = new TreeSet<>(decoded.keySet());
	  for (Integer key : keys) {
		if (doOrigin) {
		  writer.write(new AssemblyCode(0, String.format(".org 0x%04X", 0)));
		  writer.write(new AssemblyCode(0, ""));
		  doOrigin = false;
		}
		writer.write(decoded.get(key));
	  }
	  writer.write(new AssemblyCode(address, ".end"));
	} catch (IOException e) {
	  System.out.println("Error writing to output file.");
	  System.out.println(e.getMessage());
	  e.printStackTrace();
	}
  } // writeOutput()

  private static void writeRemainderOfInput(int address, ByteReader reader, AbstractWriter writer) {
	try {
	  int startOfLine = address;
	  writer.write(new AssemblyCode(startOfLine, "", ";"));
	  writer.write(new AssemblyCode(startOfLine, "", ";Unprocessed binary code from input file"));
	  writer.write(new AssemblyCode(startOfLine, "", ";"));

	  reader.seek(address);
	  Byte nextByte;
	  ArrayList<Byte> bytes = new ArrayList<>();
	  while ((nextByte = reader.getByte()) != null) {
		bytes.add(nextByte);
		address++;
		if (address % 16 == 0) {
		  writer.write(new AssemblyCode(startOfLine, bytes));
		  bytes.clear();
		  startOfLine = address;
		}
	  }
	  if (bytes.size() != 0) {
		writer.write(new AssemblyCode(startOfLine, bytes));
	  }
	} catch (IOException e) {
	  System.out.println("Error reading from input file.");
	  System.out.println(e.getMessage());
	  e.printStackTrace();
	}
  }

}
